# Programa Ingenias+ Data Science

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [1]:
#Importar numpy
import numpy as np

1. Crear un arreglo de ceros de longitud 12

In [4]:
ceros_12=np.zeros(12)
print(ceros_12)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5

In [6]:
ceros_10=np.zeros(10)
ceros_10[5]=10
print(ceros_10)

[ 0.  0.  0.  0.  0. 10.  0.  0.  0.  0.]


3. Crear un arreglo que tenga los números del 10 al 49

In [7]:
numeros_10_49=np.arange(10,50)
print(numeros_10_49)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8

In [8]:
arrays3_3=np.arange(9).reshape(3,3)
print(arrays3_3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza

In [28]:
aleatorio_enteros_100=np.random.randint(0,100,size=100)
mediaE=aleatorio_enteros_100.mean()
varianzaE=aleatorio_enteros_100.var()
print(aleatorio_enteros_100)
print(" ")
print("Media: ",mediaE)
print(" ")
print("Varianza: ",varianzaE)

[95 84 28 68 91 27 63 81 29 10 36  8 16 73 29  2 26 57 17 40 21 29 81 77
 90 40  5 20 89  0 42  3 85 37 86 68 66 56 98 41 17 71 99 44  3 84 67 26
 87 13 53 87 79 40 75 22 29  8 68 66 52 72 55 55 82 49 55 19 72  3 38  2
 10 28 96 39 60 86 58 94 56 43  4 65 36  9 57 15 14 13 58 69 39 69 28 39
 58 26 97  1]
 
Media:  47.73
 
Varianza:  844.9970999999999


In [30]:
aleatorio_decimales_100=np.random.rand(100) # 100 numeros aleatorios entre 0 y 1
mediaD=aleatorio_decimales_100.mean()
varianzaD=aleatorio_decimales_100.var()
print(aleatorio_decimales_100)
print(" ")
print("Media: ",mediaD)
print(" ")
print("Varianza: ",varianzaD)

[0.56725171 0.72070988 0.32099604 0.11170622 0.70148385 0.73191028
 0.81926083 0.47345599 0.33131647 0.9258322  0.36378458 0.67825909
 0.74726992 0.9726639  0.42821672 0.20984551 0.84702724 0.69887959
 0.04888058 0.85039042 0.10963856 0.83548585 0.61150824 0.51232784
 0.92143783 0.89914583 0.70161052 0.97274578 0.64161197 0.37447892
 0.15148163 0.26011334 0.32055787 0.11603728 0.41635403 0.98478798
 0.32143185 0.07340961 0.73562987 0.08872788 0.94262258 0.72570844
 0.66712491 0.82270567 0.61240575 0.68530842 0.03750053 0.33613776
 0.46083806 0.90913726 0.17126391 0.1908703  0.64867747 0.80024528
 0.89472584 0.6316763  0.30693328 0.47347986 0.27448364 0.69895806
 0.5364466  0.083419   0.75987034 0.02592058 0.68512845 0.13434023
 0.95910311 0.64206661 0.2617788  0.80147113 0.95265483 0.17313629
 0.66479798 0.28578314 0.57881768 0.47916685 0.2515635  0.21632554
 0.11352166 0.26345944 0.68872746 0.21233822 0.18852781 0.92374805
 0.98549243 0.11635264 0.26331686 0.56061042 0.55118734 0.8219

6. Calcular la media de un arreglo usando np.sum

In [35]:
mediaAux1=aleatorio_enteros_100.sum()/len(aleatorio_enteros_100)
print(mediaAux1)

47.73


In [36]:
mediaAux2=aleatorio_decimales_100.sum()/len(aleatorio_decimales_100)
print(mediaAux2)

0.5235317921184677


7. Calcular la varianza de un arreglo usando np.sum y np.mean

$Varianza= \frac{1}{n} \sum_{i=1}^{n}(x_i - \bar{x})^2$

In [37]:
varianzaAux1=((aleatorio_enteros_100-mediaE)**2).sum()/len(aleatorio_enteros_100)
print(varianzaAux1)

844.9970999999999


In [38]:
varianzaAux2=((aleatorio_decimales_100-mediaD)**2).sum()/len(aleatorio_decimales_100)
print(varianzaAux2)

0.08239589187517399


8. Crear un array de números aleatorios usando np.random.randn.

In [51]:
numAleatorios=np.random.randn(10)
print(numAleatorios)

[-0.50716675  2.41280847  0.88350014 -0.66091356 -0.44853549  1.97065634
  2.25562031  0.79471465 -0.45486895 -0.69373616]


In [52]:
numAleatorios.mean()

np.float64(0.5552078989600456)